- name: install containerd
  apt:
    name: containerd
    state: present

- name: create containerd configuration directory
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: 0755

- name: extract default configuration
  shell:
    cmd: containerd config default > /etc/containerd/config.toml
    creates: /etc/containerd/config.toml
  notify:
    - restart containerd

- name: enable system cgroups
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  notify:
    - restart containerd

- name: flush handlers
  meta: flush_handlers



