- name: install kubernetes key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present
  
- name: add kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    filename: kubernetes
    state: present

- name: install kubelet and friends
  apt:
    pkg:
    - kubelet
    - kubeadm
    - kubectl
    state: present

- name: hold kubelet
  dpkg_selections:
    name: kubelet
    selection: hold

- name: hold kubeadm
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: hold kubectl
  dpkg_selections:
    name: kubectl
    selection: hold

